### ISSUE TITLE
Ultrakill: Masquerade Divinity

### ISSUE THREAD

**Issue by Louw123** [xzxADIxzx/Join-and-kill-em-together#41]
When using the Jacket mod with the Masquerade Divinity. All Player models are not showing, and others have the mod except for the player.

**Comment by xzxADIxzx** [comment]
> and others have *the mod* except for the player
What do you mean? Masquerade Divinity or Jaket?

**Comment by xzxADIxzx** [comment]
Anyway, Jaket doesn't support any mod so please play without them.

**Comment by Bryan-000** [comment]
even tho jaket doesnt support mods in the newest (pre ultra_revamp) jaket update i could use masquerade divinity without it breaking jaket (just since it uses custom weppons my player model for other players would just be holding nothing at all times)
also jaket isnt misspelt jacket,
jaket is an acronym
J. oin
A. nd
K. ill
E. m'
T. ogether
so yea :P dont say "jacket"
