### ISSUE TITLE
Big desync bugs

### ISSUE THREAD

**Issue by Meganium97** [xzxADIxzx/Join-and-kill-em-together#93]
Desync is a big issue for multi-player, especially for doors and bosses.
I know you're aware of the doors that dont open no matter how many enemies are killed, but there's also a massive desync issue for bosses.
If the host dies and respawns from the checkpoint, the boss remains in place and able to attack (if grounded) permanently. This may be a side effect of the clients having a different "version" of the boss (the sandbox version).

Though, you'd only be able to get to that part if you'd gone through the level, which for certain levels, isn't possible due to the aforementioned door desync.

**Comment by kierkat10** [comment]
Jaket has not been updated for the Full Arsenal update (I know, it's been a while) since the developer has had long exams recently. I think at this point, he may be done with them, and he is updating the mod as we speak, giving us information about everything he updates and changelogs to keep us informed. He said yesterday that the update is 80% done and "will be released sometime this month (I hope)."

**Comment by xzxADIxzx** [comment]
I still need to apply to the university I chosen, but I'm mostly free, so that the speed of the development has increased.

**Comment by kierkat10** [comment]
> I still need to apply to the university I chosen, but I'm mostly free, so that the speed of the development has increased.

yay
